services:
  app:
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-conf:/etc/grafana
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    user: "472"
    
  postgres:
    image: postgres:18
    volumes:
      - pgsql-data:/var/lib/postgresql
    environment:
      PGDATA: /var/lib/postgresql/18/docker
      POSTGRES_PASSWORD: "18223005"
      POSTGRES_USER: "matheusco"
    ports:
      - 5432:5432
volumes:
  grafana-conf:
  grafana-data:
  pgsql-data: